apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-api-config
  namespace: dev
data:
  DB_HOST: "terraform-20260226174248061100000003.canuy8eysipe.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "db_test"
  DB_USER_FILE: /mnt/db-creds/username
  DB_PASSWORD_FILE: /mnt/db-creds/password

