apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.app_name }}-redis-config"
  namespace: {{ .Values.namespace }}
data:
  REDIS_URL: {{ .Values.redis.url | quote }}
  CELERY_CONCURRENCY: {{ .Values.redis.celery_concurrency | quote }}
  REDIS_STARTUP_MAX_ATTEMPTS: {{ .Values.redis.startup_max_attemps | quote }}