
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: "{{ .Values.app_name }}-net-policy-redis"
    namespace: {{ .Values.namespace }}
spec:
    podSelector:
        matchLabels:
            app.kubernetes.io/component: cache-redis
            app.kubernetes.io/name: {{ .Values.app_name }}
    policyTypes:
        - Ingress
    ingress:
        - from:
            - podSelector:
                matchLabels:
                    app.kubernetes.io/name: {{ .Values.app_name }}
                    app.kubernetes.io/component: api
          ports:
            - protocol: TCP
              port: 6379
        - from:
            - podSelector:
                matchLabels:
                    app.kubernetes.io/name: {{ .Values.app_name }}
                    app.kubernetes.io/component: worker
          ports:
            - protocol: TCP
              port: 6379


