apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Values.app_name }}-worker"
  labels:
    app.kubernetes.io/name: {{ .Values.app_name }}
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: {{ .Values.app_name }}
    tier: backend
spec:
  replicas: {{ .Values.worker_replicas_count }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app_name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app_name }}
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: {{ .Values.app_name }}
        tier: backend
    spec:
      nodeSelector:
        role: {{ .Values.app_node }}
      containers:
        - name: worker
          image: "{{ .Values.worker_image.name }}:{{ .Values.worker_image.tag }}"
          envFrom:
            - configMapRef:
                name: "{{ .Values.app_name }}-redis-config"


